/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageRouteImport } from './routes/page'
import { Route as BuilderBuilderIdLayoutRouteImport } from './routes/builder/$builderId.layout'
import { Route as BuilderBuilderIdPageRouteImport } from './routes/builder/$builderId/page'

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderBuilderIdLayoutRoute = BuilderBuilderIdLayoutRouteImport.update({
  id: '/builder/$builderId',
  path: '/builder/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderBuilderIdPageRoute = BuilderBuilderIdPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderBuilderIdLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/builder/$builderId': typeof BuilderBuilderIdLayoutRouteWithChildren
  '/builder/$builderId/': typeof BuilderBuilderIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/builder/$builderId': typeof BuilderBuilderIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/builder/$builderId': typeof BuilderBuilderIdLayoutRouteWithChildren
  '/builder/$builderId/': typeof BuilderBuilderIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/builder/$builderId' | '/builder/$builderId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder/$builderId'
  id: '__root__' | '/' | '/builder/$builderId' | '/builder/$builderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  BuilderBuilderIdLayoutRoute: typeof BuilderBuilderIdLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$builderId': {
      id: '/builder/$builderId'
      path: '/builder/$builderId'
      fullPath: '/builder/$builderId'
      preLoaderRoute: typeof BuilderBuilderIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$builderId/': {
      id: '/builder/$builderId/'
      path: '/'
      fullPath: '/builder/$builderId/'
      preLoaderRoute: typeof BuilderBuilderIdPageRouteImport
      parentRoute: typeof BuilderBuilderIdLayoutRoute
    }
  }
}

interface BuilderBuilderIdLayoutRouteChildren {
  BuilderBuilderIdPageRoute: typeof BuilderBuilderIdPageRoute
}

const BuilderBuilderIdLayoutRouteChildren: BuilderBuilderIdLayoutRouteChildren =
  {
    BuilderBuilderIdPageRoute: BuilderBuilderIdPageRoute,
  }

const BuilderBuilderIdLayoutRouteWithChildren =
  BuilderBuilderIdLayoutRoute._addFileChildren(
    BuilderBuilderIdLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  BuilderBuilderIdLayoutRoute: BuilderBuilderIdLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
